# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: FortifyScanCentralDAST@7
  inputs:
    scanCentralDastApiUrl: 'https://pentester:5001/api/'
    scanCentralCiCdToken: '2'
    sscCiToken: 'cac97901-cef5-4597-94f1-ff444b979646'